name: Crowdin - Download translations

on:
  repository_dispatch:
    types: [crowdin]

jobs:
  crowdin-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Crowdin sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: ui_l10n
          create_pull_request: true
          pull_request_title: 'UI translations'
          pull_request_body: 'The latest translations for the language files of this repo. [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'set-up-crowdin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
