name: Crowdin - Upload source

on:
  push:
    branches:
      - main
    paths:
      - 'locales/en.json'
  workflow_dispatch:

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Crowdin upload
        uses: crowdin/github-action@v2
        with:
          config: 'crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
